# -*- coding: utf-8 -*-
"""FAISS_Comp_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHh5R5gzQ2S2MqZvf9FYzTrRfA-nKqpL
"""

!pip install faiss-cpu

!pip install llama-cpp-python

!pip install fitz

!pip install PyMuPDF

!pip install -q torch

import torch
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():   print(f"GPU: {torch.cuda.get_device_name(0)}")

# Check CUDA version first
!nvcc --version

# Install llama-cpp-python with CUDA 12.x support
!pip install --no-cache-dir llama-cpp-python==0.2.90 --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu123

# Install LlamaIndex
!pip install llama-index

# Install FAISS for efficient approximate nearest neighbor search
!conda install -c pytorch faiss-gpu
!pip install faiss-cpu
from llama_cpp import Llama
import os
# Define model path
model_path = "/content/mistral.gguf"

# Download Mistral model if not already present
if not os.path.exists(model_path):
    !wget "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf" -O {model_path}
print(f"Model downloaded to {model_path}")

"""# Define model path
model_path = "/content/tinyllama.gguf"

# Download Mistral model if not already present
if not os.path.exists(model_path):
      !wget "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf" -O {model_path}
print(f"Model downloaded to {model_path}")"""

# Verify model file exists
if os.path.exists(model_path):   print(f"Model file exists. Size: {os.path.getsize(model_path) / (1024 * 1024):.2f} MB")
else:   print("Model file not found!")

# Load the model with GPU acceleration
try:
  llm = Llama(model_path=model_path,     n_gpu_layers=1,  n_ctx=2048, verbose=True)
  print("Model loaded successfully!")

except Exception as e:   print(f"Error loading model: {e}")

# FAISS Document Testing Script for Google Colab
# This script tests FAISS vector search on merger document datasets

import json
import numpy as np
import torch
import faiss
import re
import fitz  # PyMuPDF
from typing import List, Dict, Any, Tuple
from sentence_transformers import SentenceTransformer
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import os

# Install required packages first
def install_requirements():
    """Install all required packages for the experiments"""
    print("Installing required packages...")
    os.system("pip install -q sentence-transformers")
    os.system("pip install -q scikit-learn")
    os.system("pip install -q pandas")
    os.system("pip install -q pymupdf")
    print("Packages installed successfully!")

# Document Processing and Chunking
class DocumentProcessor:
    def __init__(self, chunk_size: int = 512, overlap: int = 50):
        self.chunk_size = chunk_size
        self.overlap = overlap

    def extract_text_from_pdf(self, pdf_path: str) -> str:
        """Extract text from PDF file using PyMuPDF"""
        print(f"Extracting text from PDF: {pdf_path}")

        if not os.path.exists(pdf_path):
            raise FileNotFoundError(f"PDF file not found: {pdf_path}")

        text = ""
        try:
            doc = fitz.open(pdf_path)
            print(f"PDF has {len(doc)} pages")

            for page_num in range(len(doc)):
                page = doc.load_page(page_num)
                page_text = page.get_text()
                text += page_text + "\n"

                if (page_num + 1) % 10 == 0:
                    print(f"Processed {page_num + 1} pages...")

            doc.close()
            print(f"Successfully extracted {len(text)} characters from PDF")

        except Exception as e:
            raise Exception(f"Error extracting text from PDF: {str(e)}")

        return text

    def clean_text(self, text: str) -> str:
        """Clean and normalize text"""
        # Remove excessive whitespace and newlines
        text = re.sub(r'\n+', ' ', text)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()

    def chunk_text(self, text: str) -> List[Dict[str, Any]]:
        """Split text into overlapping chunks"""
        cleaned_text = self.clean_text(text)
        words = cleaned_text.split()

        chunks = []
        start_idx = 0
        chunk_id = 0

        while start_idx < len(words):
            end_idx = min(start_idx + self.chunk_size, len(words))
            chunk_text = ' '.join(words[start_idx:end_idx])

            chunks.append({
                'id': chunk_id,
                'text': chunk_text,
                'start_word': start_idx,
                'end_word': end_idx,
                'char_start': len(' '.join(words[:start_idx])),
                'char_end': len(' '.join(words[:end_idx]))
            })

            chunk_id += 1
            start_idx = end_idx - self.overlap

            if end_idx >= len(words):
                break

        return chunks

# FAISS Vector Store
class FAISSVectorStore:
    def __init__(self, embedding_model_name: str = "all-MiniLM-L6-v2"):
        print(f"Loading embedding model: {embedding_model_name}")
        self.embedding_model = SentenceTransformer(embedding_model_name)
        self.dimension = self.embedding_model.get_sentence_embedding_dimension()
        self.index = None
        self.chunks = []
        self.embeddings = None

    def create_embeddings(self, chunks: List[Dict[str, Any]]) -> np.ndarray:
        """Create embeddings for text chunks"""
        texts = [chunk['text'] for chunk in chunks]
        print(f"Creating embeddings for {len(texts)} chunks...")

        # Create embeddings in batches to avoid memory issues
        batch_size = 32
        embeddings = []

        for i in range(0, len(texts), batch_size):
            batch_texts = texts[i:i + batch_size]
            batch_embeddings = self.embedding_model.encode(batch_texts, show_progress_bar=True)
            embeddings.append(batch_embeddings)

        return np.vstack(embeddings)

    def build_index(self, chunks: List[Dict[str, Any]]):
        """Build FAISS index from chunks"""
        self.chunks = chunks
        self.embeddings = self.create_embeddings(chunks)

        # Create FAISS index
        print("Building FAISS index...")
        self.index = faiss.IndexFlatIP(self.dimension)  # Inner product for cosine similarity

        # Normalize embeddings for cosine similarity
        faiss.normalize_L2(self.embeddings)
        self.index.add(self.embeddings)

        print(f"FAISS index built with {self.index.ntotal} vectors")

    def search(self, query: str, k: int = 5) -> List[Dict[str, Any]]:
        """Search for similar chunks"""
        if self.index is None:
            raise ValueError("Index not built. Call build_index first.")

        # Encode query
        query_embedding = self.embedding_model.encode([query])
        faiss.normalize_L2(query_embedding)

        # Search
        scores, indices = self.index.search(query_embedding, k)

        results = []
        for i, (score, idx) in enumerate(zip(scores[0], indices[0])):
            if idx != -1:  # Valid result
                results.append({
                    'chunk': self.chunks[idx],
                    'score': float(score),
                    'rank': i + 1
                })

        return results

# Evaluation Framework
class FAISSEvaluator:
    def __init__(self, vector_store: FAISSVectorStore, llm, max_context_tokens: int = 1500):
        self.vector_store = vector_store
        self.llm = llm
        self.max_context_tokens = max_context_tokens  # Leave room for prompt and response

    def estimate_tokens(self, text: str) -> int:
        """Rough token estimation (1 token ≈ 4 characters)"""
        return len(text) // 4

    def truncate_context(self, context: str, max_tokens: int) -> str:
        """Truncate context to fit within token limits"""
        estimated_tokens = self.estimate_tokens(context)

        if estimated_tokens <= max_tokens:
            return context

        # Truncate to approximately the right number of characters
        max_chars = max_tokens * 4
        if len(context) > max_chars:
            # Try to truncate at sentence boundaries
            truncated = context[:max_chars]
            last_period = truncated.rfind('.')
            last_newline = truncated.rfind('\n')

            # Cut at the latest sentence or paragraph boundary
            cut_point = max(last_period, last_newline)
            if cut_point > max_chars * 0.7:  # Only if we don't lose too much
                truncated = truncated[:cut_point + 1]

            return truncated + "..."

        return context

    def generate_answer(self, question: str, context: str) -> str:
        """Generate answer using LLM with retrieved context"""
        # Truncate context to fit within token limits
        truncated_context = self.truncate_context(context, self.max_context_tokens)

        prompt = f"""Based on the following context, answer the question concisely and accurately.

Context: {truncated_context}

Question: {question}

Answer:"""

        # Double-check prompt length
        prompt_tokens = self.estimate_tokens(prompt)
        if prompt_tokens > 1800:  # Leave room for response
            # Further truncate context if needed
            available_for_context = self.max_context_tokens - 300  # Reduce further
            truncated_context = self.truncate_context(context, available_for_context)

            prompt = f"""Based on the following context, answer the question concisely.

Context: {truncated_context}

Question: {question}

Answer:"""

        try:
            response = self.llm(prompt, max_tokens=150, temperature=0.1, stop=["\n\n", "\n"])
            return response['choices'][0]['text'].strip()
        except Exception as e:
            print(f"Error generating answer: {e}")
            print(f"Prompt length (estimated): {self.estimate_tokens(prompt)} tokens")
            return "Error: Context too long for model"

    def evaluate_question(self, question_data: Dict[str, Any], top_k: int = 3) -> Dict[str, Any]:
        """Evaluate a single question"""
        question = question_data['question']
        expected_answer = question_data.get('answer', question_data.get('expected_answer', ''))

        # Search for relevant chunks
        search_results = self.vector_store.search(question, k=top_k)

        if not search_results:
            return {
                'question': question,
                'expected_answer': expected_answer,
                'generated_answer': 'No relevant context found',
                'search_results': [],
                'top_score': 0.0,
                'context_used': '',
                'context_truncated': False
            }

        # Combine top results as context, but be smarter about length
        context_parts = []
        total_estimated_tokens = 0
        context_truncated = False

        for result in search_results:
            chunk_text = result['chunk']['text']
            chunk_tokens = self.estimate_tokens(chunk_text)

            # Stop adding chunks if we're getting close to limit
            if total_estimated_tokens + chunk_tokens > self.max_context_tokens:
                context_truncated = True
                break

            context_parts.append(f"[Score: {result['score']:.3f}] {chunk_text}")
            total_estimated_tokens += chunk_tokens

        # If no chunks fit, use just the top one but truncated
        if not context_parts and search_results:
            top_chunk = search_results[0]['chunk']['text']
            truncated_chunk = self.truncate_context(top_chunk, self.max_context_tokens)
            context_parts = [f"[Score: {search_results[0]['score']:.3f}] {truncated_chunk}"]
            context_truncated = True

        combined_context = "\n\n".join(context_parts)

        # Generate answer
        generated_answer = self.generate_answer(question, combined_context)

        return {
            'question': question,
            'expected_answer': expected_answer,
            'generated_answer': generated_answer,
            'search_results': search_results,
            'top_score': search_results[0]['score'] if search_results else 0.0,
            'context_used': combined_context,
            'context_truncated': context_truncated,
            'num_chunks_used': len(context_parts),
            'estimated_tokens': self.estimate_tokens(combined_context)
        }

    def evaluate_dataset(self, dataset: List[Dict[str, Any]], top_k: int = 3) -> Dict[str, Any]:
        """Evaluate entire dataset"""
        print(f"Evaluating {len(dataset)} questions...")

        results = []
        for i, question_data in enumerate(dataset):
            print(f"Processing question {i+1}/{len(dataset)}")
            result = self.evaluate_question(question_data, top_k)
            results.append(result)

        # Calculate metrics
        avg_top_score = np.mean([r['top_score'] for r in results])
        truncated_count = sum(1 for r in results if r.get('context_truncated', False))
        avg_tokens_used = np.mean([r.get('estimated_tokens', 0) for r in results])

        return {
            'results': results,
            'metrics': {
                'avg_top_score': avg_top_score,
                'total_questions': len(results),
                'context_truncated_count': truncated_count,
                'avg_tokens_used': avg_tokens_used
            }
        }

# Main Experiment Runner
class ExperimentRunner:
    def __init__(self, llm, chunk_size: int = 256, overlap: int = 32):  # Smaller chunks
        self.llm = llm
        self.processor = DocumentProcessor(chunk_size=chunk_size, overlap=overlap)
        self.vector_store = FAISSVectorStore()

    def load_dataset(self, json_path: str) -> List[Dict[str, Any]]:
        """Load dataset from JSON file"""
        print(f"Loading dataset from: {json_path}")

        if not os.path.exists(json_path):
            raise FileNotFoundError(f"JSON file not found: {json_path}")

        try:
            with open(json_path, 'r', encoding='utf-8') as file:
                data = json.load(file)

            print(f"Successfully loaded {len(data)} questions from {json_path}")
            return data

        except Exception as e:
            raise Exception(f"Error loading JSON file {json_path}: {str(e)}")

    def prepare_document_from_pdf(self, pdf_path: str):
        """Process PDF document and index it"""
        print("Extracting text from PDF...")
        document_text = self.processor.extract_text_from_pdf(pdf_path)

        print("Processing document...")
        chunks = self.processor.chunk_text(document_text)
        print(f"Created {len(chunks)} chunks")

        print("Building FAISS index...")
        self.vector_store.build_index(chunks)

        return document_text

    def prepare_document(self, document_text: str):
        """Process and index document text"""
        print("Processing document...")
        chunks = self.processor.chunk_text(document_text)
        print(f"Created {len(chunks)} chunks")

        print("Building FAISS index...")
        self.vector_store.build_index(chunks)

    def run_experiment(self, dataset: List[Dict[str, Any]], experiment_name: str, top_k: int = 3):
        """Run complete experiment"""
        print(f"\n{'='*50}")
        print(f"Running {experiment_name}")
        print(f"{'='*50}")

        evaluator = FAISSEvaluator(self.vector_store, self.llm)
        results = evaluator.evaluate_dataset(dataset, top_k)

        # Display results
        self.display_results(results, experiment_name)

        return results

    def display_results(self, results: Dict[str, Any], experiment_name: str):
        """Display experiment results"""
        metrics = results['metrics']
        print(f"\n{experiment_name} Results:")
        print(f"Average Top Score: {metrics['avg_top_score']:.4f}")
        print(f"Total Questions: {metrics['total_questions']}")
        print(f"Context Truncated: {metrics['context_truncated_count']}/{metrics['total_questions']} questions")
        print(f"Average Tokens Used: {metrics['avg_tokens_used']:.0f}")

        print("\nSample Results:")
        for i, result in enumerate(results['results'][:3]):  # Show first 3
            print(f"\n--- Question {i+1} ---")
            print(f"Q: {result['question']}")
            print(f"Expected: {result['expected_answer']}")
            print(f"Generated: {result['generated_answer']}")
            print(f"Top Score: {result['top_score']:.4f}")
            print(f"Tokens Used: {result.get('estimated_tokens', 0)}")
            if result.get('context_truncated', False):
                print("⚠️  Context was truncated due to length")

# Example usage and test data
def create_sample_document():
    """Create sample merger document for testing"""
    return """
MERGER AND LISTING PROSPECTUS
SEPTEMBER 2, 2021

The Boards of Directors of Valmet Oyj ("Valmet") and Neles Corporation ("Neles") have, on July 2, 2021, agreed upon the combination of the
two companies by signing a combination agreement (the "Combination Agreement") and a merger plan (the "Merger Plan"), according to
which Neles shall be merged into Valmet through a statutory absorption merger in accordance with the Limited Liability Companies Act
(624/2006, as amended) (the "Finnish Companies Act") whereby all assets and liabilities of Neles shall be transferred without a liquidation
procedure to Valmet (the "Merger"). The Boards of Directors of Valmet and Neles have on August 9, 2021 proposed that the Extraordinary
General Meetings ("EGM") of Valmet and Neles convened to be held on September 22, 2021 would resolve upon the Merger as set forth in the
Merger Plan. The completion of the Merger is subject to, among others, approval by the EGMs of Valmet and Neles, obtaining necessary merger
control approvals and other customary closing conditions.

FINANCIAL INFORMATION

The following table sets forth a summary of Valmet's key financial information as at the dates and for the periods indicated:

As at and for the six months ended June 30, As at and for the year ended December 31,
EUR million, unless otherwise indicated 2021 2020 2020

Consolidated Statement of Income
Net sales 1,801 1,567 3,983
Operating profit 142 89 312
Profit before income taxes 131 78 291
"""

def run_complete_test(pdf_path: str, exp1_json: str = "qa_dataset(EXP1).json", exp2_json: str = "cross_qa_dataset(EXP2).json"):
    """Run complete FAISS testing pipeline with PDF and JSON files"""

    # Install requirements
    install_requirements()

    # Your LLM setup code should be run before this function
    print("Note: Make sure your LLM is loaded as 'llm' variable before running this function")

    try:
        # Initialize experiment runner
        runner = ExperimentRunner(llm)  # This assumes 'llm' is available from your setup

        # Load datasets from JSON files
        print("\n" + "="*60)
        print("LOADING DATASETS")
        print("="*60)

        experiment1_data = runner.load_dataset(exp1_json)
        experiment2_data = runner.load_dataset(exp2_json)

        # Extract and process PDF document
        print("\n" + "="*60)
        print("PROCESSING PDF DOCUMENT")
        print("="*60)

        document_text = runner.prepare_document_from_pdf(pdf_path)

        # Show document stats
        print(f"\nDocument Statistics:")
        print(f"- Total characters: {len(document_text):,}")
        print(f"- Total words: {len(document_text.split()):,}")
        print(f"- Number of chunks: {len(runner.vector_store.chunks)}")

        # Run experiments
        print("\n" + "="*60)
        print("RUNNING EXPERIMENTS")
        print("="*60)

        exp1_results = runner.run_experiment(experiment1_data, "Experiment 1: Basic QA Dataset", top_k=3)
        exp2_results = runner.run_experiment(experiment2_data, "Experiment 2: Cross QA Dataset", top_k=3)

        # Save results
        print("\n" + "="*60)
        print("SAVING RESULTS")
        print("="*60)

        # Save detailed results to JSON files
        with open('experiment1_results.json', 'w', encoding='utf-8') as f:
            json.dump(exp1_results, f, indent=2, ensure_ascii=False)

        with open('experiment2_results.json', 'w', encoding='utf-8') as f:
            json.dump(exp2_results, f, indent=2, ensure_ascii=False)

        print("Results saved to 'experiment1_results.json' and 'experiment2_results.json'")

        return exp1_results, exp2_results

    except Exception as e:
        print(f"Error running experiments: {str(e)}")
        return None, None

def run_experiments_with_files(pdf_path: str, exp1_json: str, exp2_json: str):
    """Alternative function to run experiments with custom file paths"""
    return run_complete_test(pdf_path, exp1_json, exp2_json)

# File validation helper
def validate_files(pdf_path: str, exp1_json: str = "qa_dataset(EXP1).json", exp2_json: str = "cross_qa_dataset(EXP2).json"):
    """Validate that all required files exist"""
    missing_files = []

    if not os.path.exists(pdf_path):
        missing_files.append(f"PDF file: {pdf_path}")

    if not os.path.exists(exp1_json):
        missing_files.append(f"Experiment 1 JSON: {exp1_json}")

    if not os.path.exists(exp2_json):
        missing_files.append(f"Experiment 2 JSON: {exp2_json}")

    if missing_files:
        print("Missing files:")
        for file in missing_files:
            print(f"  - {file}")
        return False

    print("All required files found!")
    return True

# Instructions for usage
print("""
FAISS Testing Script Instructions:

1. First, run your LLM setup code to initialize the 'llm' variable

2. Prepare your files:
   - PDF document containing the merger text
   - qa_dataset(EXP1).json - JSON file with experiment 1 questions
   - cross_qa_dataset(EXP2).json - JSON file with experiment 2 questions

3. Validate files exist:
   validate_files("your_document.pdf")

4. Run experiments:
   exp1_results, exp2_results = run_complete_test("your_document.pdf")

5. Or with custom JSON file names:
   exp1_results, exp2_results = run_experiments_with_files(
       "your_document.pdf",
       "custom_exp1.json",
       "custom_exp2.json"
   )

Example usage:
   # Check files
   validate_files("merger_document.pdf")

   # Run experiments
   results1, results2 = run_complete_test("merger_document.pdf")

Key Parameters:
- chunk_size: Number of words per chunk (default: 512)
- overlap: Number of overlapping words between chunks (default: 50)
- top_k: Number of similar chunks to retrieve (default: 3)
- embedding_model: SentenceTransformer model for embeddings (default: "all-MiniLM-L6-v2")

Output:
- Results will be saved as 'experiment1_results.json' and 'experiment2_results.json'
- Console output shows detailed progress and sample results
""")

# Execute FAISS Experiments - Ready to Run
# Run this code after loading the main FAISS script and your LLM

import os

# Define file paths
PDF_PATH = "/content/valmet_merger.pdf"
EXP1_JSON = "/content/qa_dataset (EXP1).json"
EXP2_JSON = "/content/cross_qa_dataset(EXP2).json"

print("="*70)
print("FAISS EXPERIMENTS - VALMET MERGER DOCUMENT")
print("="*70)

# Step 1: Verify LLM is loaded
print("\n1. Checking LLM status...")
try:
    print(f"✓ LLM loaded successfully: {type(llm)}")
    # Test LLM with a simple prompt
    test_response = llm("Hello", max_tokens=5, temperature=0.1)
    print("✓ LLM is responding correctly")
except NameError:
    print("❌ ERROR: LLM not loaded!")
    print("Please run your LLM setup code first:")
    print("- Load the model using llama-cpp-python")
    print("- Make sure the 'llm' variable is available")
    exit()
except Exception as e:
    print(f"❌ ERROR: LLM test failed: {e}")
    exit()

# Step 2: Validate all files exist
print("\n2. Validating files...")
if validate_files(PDF_PATH, EXP1_JSON, EXP2_JSON):
    print("✓ All files found!")

    # Show file sizes
    pdf_size = os.path.getsize(PDF_PATH) / (1024 * 1024)  # MB
    exp1_size = os.path.getsize(EXP1_JSON) / 1024  # KB
    exp2_size = os.path.getsize(EXP2_JSON) / 1024  # KB

    print(f"  - PDF size: {pdf_size:.1f} MB")
    print(f"  - Experiment 1 JSON: {exp1_size:.1f} KB")
    print(f"  - Experiment 2 JSON: {exp2_size:.1f} KB")
else:
    print("❌ Some files are missing. Please check the paths:")
    print(f"  - PDF: {PDF_PATH}")
    print(f"  - EXP1: {EXP1_JSON}")
    print(f"  - EXP2: {EXP2_JSON}")
    exit()

# Step 3: Run the experiments
print("\n3. Starting experiments...")
print("This may take several minutes depending on document size...")

try:
    # Run experiments with your specific file paths
    exp1_results, exp2_results = run_experiments_with_files(
        PDF_PATH,
        EXP1_JSON,
        EXP2_JSON
    )

    if exp1_results and exp2_results:
        print("\n" + "="*70)
        print("✓ EXPERIMENTS COMPLETED SUCCESSFULLY!")
        print("="*70)

        # Display summary results
        print(f"\nEXPERIMENT 1 SUMMARY:")
        print(f"  - Questions processed: {len(exp1_results['results'])}")
        print(f"  - Average similarity score: {exp1_results['metrics']['avg_top_score']:.4f}")
        print(f"  - Context truncated: {exp1_results['metrics']['context_truncated_count']}/{exp1_results['metrics']['total_questions']} questions")
        print(f"  - Average tokens used: {exp1_results['metrics']['avg_tokens_used']:.0f}")

        print(f"\nEXPERIMENT 2 SUMMARY:")
        print(f"  - Questions processed: {len(exp2_results['results'])}")
        print(f"  - Average similarity score: {exp2_results['metrics']['avg_top_score']:.4f}")
        print(f"  - Context truncated: {exp2_results['metrics']['context_truncated_count']}/{exp2_results['metrics']['total_questions']} questions")
        print(f"  - Average tokens used: {exp2_results['metrics']['avg_tokens_used']:.0f}")

        # Show some sample results
        print(f"\nSAMPLE RESULTS FROM EXPERIMENT 1:")
        for i, result in enumerate(exp1_results['results'][:2]):
            print(f"\n--- Question {i+1} ---")
            print(f"Q: {result['question'][:100]}{'...' if len(result['question']) > 100 else ''}")
            print(f"Expected: {result['expected_answer'][:100]}{'...' if len(result['expected_answer']) > 100 else ''}")
            print(f"Generated: {result['generated_answer'][:100]}{'...' if len(result['generated_answer']) > 100 else ''}")
            print(f"Similarity Score: {result['top_score']:.4f}")

        print(f"\nSAMPLE RESULTS FROM EXPERIMENT 2:")
        for i, result in enumerate(exp2_results['results'][:2]):
            print(f"\n--- Question {i+1} ---")
            print(f"Q: {result['question'][:100]}{'...' if len(result['question']) > 100 else ''}")
            print(f"Expected: {result['expected_answer'][:100]}{'...' if len(result['expected_answer']) > 100 else ''}")
            print(f"Generated: {result['generated_answer'][:100]}{'...' if len(result['generated_answer']) > 100 else ''}")
            print(f"Similarity Score: {result['top_score']:.4f}")

        print(f"\n📁 Detailed results saved to:")
        print(f"  - experiment1_results.json")
        print(f"  - experiment2_results.json")

    else:
        print("\n❌ EXPERIMENTS FAILED!")
        print("Check the error messages above for details.")

except Exception as e:
    print(f"\n❌ ERROR during experiments: {str(e)}")
    print("\nTroubleshooting tips:")
    print("1. Make sure your LLM is properly loaded")
    print("2. Check that all files are accessible")
    print("3. Ensure you have enough memory/GPU resources")
    print("4. Check the JSON file formats are correct")

print("\n" + "="*70)
print("EXECUTION COMPLETE")
print("="*70)

# LLM Answer Grading Script
# Grades the generated answers from FAISS experiments using LLM evaluation

import json
import numpy as np
import pandas as pd
from typing import List, Dict, Any, Tuple
import re
import os

class LLMAnswerGrader:
    def __init__(self, llm):
        """Initialize grader with LLM for evaluation"""
        self.llm = llm
        self.grading_prompt_template = """You are an expert evaluator assessing the quality of answers to questions about a merger document.

Question: {question}
Expected Answer: {expected_answer}
Actual Answer: {actual_answer}

Grading criteria:
1. Correctness: Is the information in the actual answer factually correct according to the expected answer?
2. Completeness: Does the actual answer cover all important points from the expected answer?
3. Relevance: Does the actual answer directly address the question being asked?
4. Precision: Is the actual answer concise and to the point without unnecessary information?

Please consider these criteria and provide:
1. A score between 0.0 and 1.0, where:
   - 0.0-0.2: Completely incorrect or irrelevant
   - 0.2-0.4: Mostly incorrect with minor valid points
   - 0.4-0.6: Partially correct but missing key information
   - 0.6-0.8: Mostly correct with minor issues
   - 0.8-1.0: Completely correct and comprehensive

2. A brief explanation of your grading (1-2 sentences)

FORMAT YOUR RESPONSE EXACTLY LIKE THIS:
Score: [number between 0 and 1]
Explanation: [brief explanation]"""

    def grade_single_answer_simple(self, question: str, expected: str, actual: str) -> Dict[str, Any]:
        """Simplified grading with more flexible prompt"""

        # Handle empty or error answers
        if not actual or actual.strip() in ["", "No relevant context found", "Error: Context too long for model"]:
            return {
                'score': 0.0,
                'explanation': "No valid answer provided",
                'raw_response': "N/A - Empty answer"
            }

        # Simplified prompt that's more likely to get proper format
        simple_prompt = f"""Grade this answer on a scale of 0.0 to 1.0:

Question: {question}
Expected: {expected}
Actual: {actual}

Give a score from 0.0 (completely wrong) to 1.0 (perfect) and explain why.

Score: """

        try:
            response = self.llm(simple_prompt, max_tokens=150, temperature=0.1, stop=["\n"])
            raw_response = response['choices'][0]['text'].strip()

            # Try to extract just a number first
            number_match = re.search(r'([0-9]*\.?[0-9]+)', raw_response)
            if number_match:
                score = float(number_match.group(1))
                score = max(0.0, min(1.0, score))

                # Get explanation by prompting again
                explain_prompt = f"""Why did you give this answer a score of {score}?

Question: {question}
Expected: {expected}
Actual: {actual}

Brief explanation: """

                explain_response = self.llm(explain_prompt, max_tokens=100, temperature=0.1)
                explanation = explain_response['choices'][0]['text'].strip()

            else:
                score = 0.0
                explanation = f"Could not parse score from: {raw_response}"

            return {
                'score': score,
                'explanation': explanation,
                'raw_response': raw_response
            }

        except Exception as e:
            print(f"Error in simple grading: {e}")
            return {
                'score': 0.0,
                'explanation': f"Grading error: {str(e)}",
                'raw_response': "Error"
            }
        """Grade a single answer using LLM evaluation"""

        # Handle empty or error answers
        if not actual or actual.strip() in ["", "No relevant context found", "Error: Context too long for model"]:
            return {
                'score': 0.0,
                'explanation': "No valid answer provided",
                'raw_response': "N/A - Empty answer"
            }

        # Create grading prompt
        prompt = self.grading_prompt_template.format(
            question=question,
            expected_answer=expected,
            actual_answer=actual
        )

        try:
            # Get LLM evaluation with more specific parameters
            response = self.llm(
                prompt,
                max_tokens=250,  # Increased for full response
                temperature=0.1,
                stop=["\n\nQuestion:", "\n\n\n"]  # Better stop tokens
            )
            raw_response = response['choices'][0]['text'].strip()

            # Parse score and explanation
            score, explanation = self.parse_grading_response(raw_response)

            return {
                'score': score,
                'explanation': explanation,
                'raw_response': raw_response
            }

        except Exception as e:
            print(f"Error grading answer: {e}")
            return {
                'score': 0.0,
                'explanation': f"Error during grading: {str(e)}",
                'raw_response': "Error"
            }

    def parse_grading_response(self, response: str) -> Tuple[float, str]:
        """Parse the LLM grading response to extract score and explanation"""
        try:
            print(f"Debug - Raw response: '{response}'")  # Debug output

            # Try multiple parsing strategies
            score = 0.0
            explanation = "Could not parse response"

            # Strategy 1: Look for "Score:" pattern
            score_match = re.search(r'Score:\s*([0-9]*\.?[0-9]+)', response, re.IGNORECASE)
            if score_match:
                score = float(score_match.group(1))
                score = max(0.0, min(1.0, score))  # Clamp to valid range
            else:
                # Strategy 2: Look for any decimal number (fallback)
                number_match = re.search(r'([0-9]*\.?[0-9]+)', response)
                if number_match:
                    potential_score = float(number_match.group(1))
                    if 0.0 <= potential_score <= 1.0:
                        score = potential_score

            # Strategy 1: Look for "Explanation:" pattern
            explanation_match = re.search(r'Explanation:\s*(.+)', response, re.IGNORECASE | re.DOTALL)
            if explanation_match:
                explanation = explanation_match.group(1).strip()
            else:
                # Strategy 2: Look for text after score (fallback)
                if score_match:
                    # Get everything after the score line
                    score_end = score_match.end()
                    remaining_text = response[score_end:].strip()
                    if remaining_text:
                        # Remove any remaining "Explanation:" prefix
                        remaining_text = re.sub(r'^Explanation:\s*', '', remaining_text, flags=re.IGNORECASE)
                        explanation = remaining_text
                else:
                    # Strategy 3: Use the whole response as explanation if no score found
                    explanation = response.strip()

            # Clean up explanation
            explanation = explanation.replace('\n', ' ').strip()
            if len(explanation) > 200:  # Truncate very long explanations
                explanation = explanation[:200] + "..."

            return score, explanation

        except Exception as e:
            print(f"Error parsing grading response: {e}")
            return 0.0, f"Parse error: {str(e)}"

    def grade_experiment_results(self, results_file: str, experiment_name: str) -> Dict[str, Any]:
        """Grade all answers in an experiment results file"""
        print(f"\n{'='*60}")
        print(f"GRADING {experiment_name}")
        print(f"{'='*60}")

        # Load results
        try:
            with open(results_file, 'r', encoding='utf-8') as f:
                experiment_data = json.load(f)
        except Exception as e:
            print(f"Error loading results file {results_file}: {e}")
            return None

        results = experiment_data['results']
        graded_results = []

        print(f"Grading {len(results)} answers...")

        for i, result in enumerate(results):
            print(f"Grading answer {i+1}/{len(results)}...")

            question = result['question']
            expected = result['expected_answer']
            actual = result['generated_answer']

            # Grade the answer - try main method first, then fallback to simple
            grading = self.grade_single_answer_simple(question, expected, actual)

            # If parsing failed, try simple method
            if grading['explanation'] == "Could not parse explanation from response":
                print(f"  Retrying with simple grading method...")
                grading = self.grade_single_answer_simple(question, expected, actual)

            # Show debug info for first few answers
            if i < 3:  # Debug first 3 answers
                print(f"  Question: {question[:50]}...")
                print(f"  Raw LLM response: {grading['raw_response']}")
                print(f"  Parsed score: {grading['score']}")
                print(f"  Parsed explanation: {grading['explanation'][:100]}...")

            # Combine original result with grading
            graded_result = {
                **result,  # Original data
                'llm_score': grading['score'],
                'llm_explanation': grading['explanation'],
                'llm_raw_response': grading['raw_response']
            }

            graded_results.append(graded_result)

        # Calculate grading statistics
        scores = [r['llm_score'] for r in graded_results]
        grading_stats = {
            'total_answers': len(scores),
            'avg_score': np.mean(scores),
            'median_score': np.median(scores),
            'std_score': np.std(scores),
            'min_score': np.min(scores),
            'max_score': np.max(scores),
            'score_distribution': self.get_score_distribution(scores)
        }

        return {
            'experiment_name': experiment_name,
            'graded_results': graded_results,
            'original_metrics': experiment_data['metrics'],
            'grading_stats': grading_stats
        }

    def get_score_distribution(self, scores: List[float]) -> Dict[str, int]:
        """Calculate distribution of scores by grade bands"""
        distribution = {
            '0.0-0.2 (Poor)': 0,
            '0.2-0.4 (Below Average)': 0,
            '0.4-0.6 (Average)': 0,
            '0.6-0.8 (Good)': 0,
            '0.8-1.0 (Excellent)': 0
        }

        for score in scores:
            if score <= 0.2:
                distribution['0.0-0.2 (Poor)'] += 1
            elif score <= 0.4:
                distribution['0.2-0.4 (Below Average)'] += 1
            elif score <= 0.6:
                distribution['0.4-0.6 (Average)'] += 1
            elif score <= 0.8:
                distribution['0.6-0.8 (Good)'] += 1
            else:
                distribution['0.8-1.0 (Excellent)'] += 1

        return distribution

    def display_grading_results(self, graded_data: Dict[str, Any]):
        """Display comprehensive grading results"""
        if not graded_data:
            print("No grading data to display")
            return

        experiment_name = graded_data['experiment_name']
        grading_stats = graded_data['grading_stats']
        graded_results = graded_data['graded_results']

        print(f"\n{experiment_name} - GRADING RESULTS")
        print("="*60)

        # Overall statistics
        print(f"\nOVERALL GRADING STATISTICS:")
        print(f"  Average Score: {grading_stats['avg_score']:.3f}")
        print(f"  Median Score: {grading_stats['median_score']:.3f}")
        print(f"  Standard Deviation: {grading_stats['std_score']:.3f}")
        print(f"  Score Range: {grading_stats['min_score']:.3f} - {grading_stats['max_score']:.3f}")

        # Score distribution
        print(f"\nSCORE DISTRIBUTION:")
        for grade_band, count in grading_stats['score_distribution'].items():
            percentage = (count / grading_stats['total_answers']) * 100
            print(f"  {grade_band}: {count} answers ({percentage:.1f}%)")

        # Original FAISS metrics
        original_metrics = graded_data['original_metrics']
        print(f"\nORIGINAL FAISS METRICS:")
        print(f"  Average Similarity Score: {original_metrics['avg_top_score']:.3f}")
        print(f"  Context Truncated: {original_metrics.get('context_truncated_count', 0)}/{original_metrics['total_questions']}")

        # Sample graded results
        print(f"\nSAMPLE GRADED RESULTS:")
        # Show best, worst, and median examples
        sorted_results = sorted(graded_results, key=lambda x: x['llm_score'])

        # Worst example
        if sorted_results:
            worst = sorted_results[0]
            print(f"\n--- LOWEST SCORING ANSWER (Score: {worst['llm_score']:.2f}) ---")
            print(f"Q: {worst['question'][:100]}{'...' if len(worst['question']) > 100 else ''}")
            print(f"Expected: {worst['expected_answer'][:100]}{'...' if len(worst['expected_answer']) > 100 else ''}")
            print(f"Generated: {worst['generated_answer'][:100]}{'...' if len(worst['generated_answer']) > 100 else ''}")
            print(f"Explanation: {worst['llm_explanation']}")

        # Best example
        if sorted_results:
            best = sorted_results[-1]
            print(f"\n--- HIGHEST SCORING ANSWER (Score: {best['llm_score']:.2f}) ---")
            print(f"Q: {best['question'][:100]}{'...' if len(best['question']) > 100 else ''}")
            print(f"Expected: {best['expected_answer'][:100]}{'...' if len(best['expected_answer']) > 100 else ''}")
            print(f"Generated: {best['generated_answer'][:100]}{'...' if len(best['generated_answer']) > 100 else ''}")
            print(f"Explanation: {best['llm_explanation']}")

        # Median example
        if len(sorted_results) > 2:
            median_idx = len(sorted_results) // 2
            median = sorted_results[median_idx]
            print(f"\n--- MEDIAN SCORING ANSWER (Score: {median['llm_score']:.2f}) ---")
            print(f"Q: {median['question'][:100]}{'...' if len(median['question']) > 100 else ''}")
            print(f"Expected: {median['expected_answer'][:100]}{'...' if len(median['expected_answer']) > 100 else ''}")
            print(f"Generated: {median['generated_answer'][:100]}{'...' if len(median['generated_answer']) > 100 else ''}")
            print(f"Explanation: {median['llm_explanation']}")

    def save_graded_results(self, graded_data: Dict[str, Any], output_file: str):
        """Save graded results to JSON file"""
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(graded_data, f, indent=2, ensure_ascii=False)
            print(f"\nGraded results saved to: {output_file}")
        except Exception as e:
            print(f"Error saving graded results: {e}")

    def create_grading_summary_report(self, exp1_graded: Dict[str, Any], exp2_graded: Dict[str, Any]):
        """Create a comparative summary report"""
        print(f"\n{'='*80}")
        print("COMPREHENSIVE GRADING SUMMARY REPORT")
        print(f"{'='*80}")

        if exp1_graded:
            exp1_stats = exp1_graded['grading_stats']
        if exp2_graded:
            exp2_stats = exp2_graded['grading_stats']

        # Comparison table
        print(f"\nCOMPARATIVE ANALYSIS:")
        print(f"{'Metric':<25} {'Experiment 1':<15} {'Experiment 2':<15}")
        print("-" * 55)

        if exp1_graded and exp2_graded:
            print(f"{'Average Score':<25} {exp1_stats['avg_score']:<15.3f} {exp2_stats['avg_score']:<15.3f}")
            print(f"{'Median Score':<25} {exp1_stats['median_score']:<15.3f} {exp2_stats['median_score']:<15.3f}")
            print(f"{'Best Score':<25} {exp1_stats['max_score']:<15.3f} {exp2_stats['max_score']:<15.3f}")
            print(f"{'Worst Score':<25} {exp1_stats['min_score']:<15.3f} {exp2_stats['min_score']:<15.3f}")
            print(f"{'Std Deviation':<25} {exp1_stats['std_score']:<15.3f} {exp2_stats['std_score']:<15.3f}")

            # Performance insights
            print(f"\nPERFORMANCE INSIGHTS:")
            if exp1_stats['avg_score'] > exp2_stats['avg_score']:
                diff = exp1_stats['avg_score'] - exp2_stats['avg_score']
                print(f"✓ Experiment 1 performed better by {diff:.3f} points on average")
            elif exp2_stats['avg_score'] > exp1_stats['avg_score']:
                diff = exp2_stats['avg_score'] - exp1_stats['avg_score']
                print(f"✓ Experiment 2 performed better by {diff:.3f} points on average")
            else:
                print(f"≈ Both experiments performed equally well")

            # Quality analysis
            exp1_excellent = exp1_stats['score_distribution']['0.8-1.0 (Excellent)']
            exp2_excellent = exp2_stats['score_distribution']['0.8-1.0 (Excellent)']

            print(f"\nQUALITY ANALYSIS:")
            print(f"  Experiment 1: {exp1_excellent}/{exp1_stats['total_answers']} excellent answers ({exp1_excellent/exp1_stats['total_answers']*100:.1f}%)")
            print(f"  Experiment 2: {exp2_excellent}/{exp2_stats['total_answers']} excellent answers ({exp2_excellent/exp2_stats['total_answers']*100:.1f}%)")

# Main grading execution function
def run_answer_grading(llm, exp1_results_file: str = "experiment1_results.json", exp2_results_file: str = "experiment2_results.json"):
    """Run complete answer grading for both experiments"""

    print("="*80)
    print("LLM ANSWER GRADING SYSTEM")
    print("="*80)

    # Initialize grader
    grader = LLMAnswerGrader(llm)

    # Grade experiment 1
    exp1_graded = None
    if os.path.exists(exp1_results_file):
        exp1_graded = grader.grade_experiment_results(exp1_results_file, "EXPERIMENT 1")
        if exp1_graded:
            grader.display_grading_results(exp1_graded)
            grader.save_graded_results(exp1_graded, "experiment1_graded.json")
    else:
        print(f"Warning: {exp1_results_file} not found")

    # Grade experiment 2
    exp2_graded = None
    if os.path.exists(exp2_results_file):
        exp2_graded = grader.grade_experiment_results(exp2_results_file, "EXPERIMENT 2")
        if exp2_graded:
            grader.display_grading_results(exp2_graded)
            grader.save_graded_results(exp2_graded, "experiment2_graded.json")
    else:
        print(f"Warning: {exp2_results_file} not found")

    # Create comparative summary
    if exp1_graded or exp2_graded:
        grader.create_grading_summary_report(exp1_graded, exp2_graded)

    return exp1_graded, exp2_graded

# Instructions
print("""
LLM Answer Grading Script Instructions:

USAGE:
1. Make sure you have already run the FAISS experiments and have result files:
   - experiment1_results.json
   - experiment2_results.json

2. Run the grading:
   exp1_graded, exp2_graded = run_answer_grading(llm)

3. The script will:
   - Grade each answer using your LLM
   - Provide detailed statistics and analysis
   - Show best/worst/median examples
   - Create comparative analysis between experiments
   - Save graded results to new JSON files

OUTPUTS:
- experiment1_graded.json (detailed graded results)
- experiment2_graded.json (detailed graded results)
- Console output with comprehensive analysis

The grading uses a 0.0-1.0 scale evaluating:
- Correctness, Completeness, Relevance, and Precision
""")

exp1_graded, exp2_graded = run_answer_grading(llm)